export const block = (type, parents = [], attrs = {}, isEmbed = false) => ({
  type: "block",
  value: { type, parents, attrs, isEmbed },
})
export const text = (value, marks) => (marks ? { type: "text", value, marks } : { type: "text", value })

// Everything lush writes, in one note.
export const LUSH_NOTE = [
  block("heading", [], { level: 1 }),
  text("A lush note"),
  block("paragraph"),
  text("plain "),
  text("bold", { strong: true }),
  text(" "),
  text("italic", { em: true }),
  text(" "),
  text("link", { link: "https://example.com/a?b=c" }),
  text(" "),
  text("sky", { highlight: "sky" }),
  text(" "),
  text("under", { underline: true }),
  text(" "),
  text("struck", { strikethrough: true }),
  text(" x"),
  text("2", { superscript: true }),
  text(" H"),
  text("2", { subscript: true }),
  text("O "),
  text("serif", { font: "serif" }),
  text(" "),
  text("hand", { font: "hand" }),
  text(" "),
  text("mono", { code: true }),
  text(" "),
  text("mystery", { mystery: "kept" }),
  block("paragraph", [], { indent: 2 }),
  text("indented twice"),
  block("heading", [], { level: 2, indent: 1 }),
  text("An indented heading"),
  block("code-block", [], { language: "swift" }),
  text("let a = 1"),
  block("code-block", [], { language: "swift" }),
  text("let b = 2"),
  block("unordered-list-item"),
  text("bullet"),
  block("unordered-list-item", ["unordered-list-item"]),
  text("nested bullet"),
  block("ordered-list-item"),
  text("first"),
  block("ordered-list-item"),
  text("second"),
  block("todo-list-item"),
  text("open"),
  block("todo-list-item", [], { checked: true }),
  text("done"),
  block("todo-list-item", [], { state: "canceled" }),
  text("canceled"),
  block("todo-list-item", [], { state: "pending" }),
  text("pending"),
  block("blockquote"),
  text("quoted soft break"),
  block("paragraph", ["blockquote"]),
  text("second quote line"),
  block("embed", [], { url: "automerge:2j9knpCseyhnK8izDmLpGP5WMdZQ", alt: "a photo", width: 320, height: 200 }, true),
  block("paragraph"),
  text("after the embed"),
  block(
    "context",
    [],
    {
      ts: "2026-09-27T10:11:12+01:00",
      tz: "Europe/London",
      location: "Leeds",
      lat: 53.8,
      lon: -1.55,
      weather: "11°C, drizzle",
      nowPlaying: "Stereolab — French Disko",
      pending: true,
    },
    true,
  ),
  block(
    "calendar-event",
    [],
    { event: "ev1", kind: "event", title: "Tea", start: "2026-09-28T16:00:00", end: "2026-09-28T17:00:00", color: "#FF4D97" },
    true,
  ),
  block("html", [], { html: "<b>hi</b>" }, true),
  block("table"),
  block("table-row", ["table"]),
  block("table-header-cell", ["table", "table-row"]),
  text("Name"),
  block("table-header-cell", ["table", "table-row"]),
  text("Notes"),
  block("table-row", ["table"]),
  block("table-cell", ["table", "table-row"]),
  text("chee"),
  block("table-cell", ["table", "table-row"]),
  text("line one"),
  block("paragraph", ["table", "table-row", "table-cell"]),
  text("line two"),
  block("columns"),
  block("column", ["columns"]),
  text("left"),
  block("column", ["columns"]),
  text("right"),
  block("paragraph", ["columns", "column"]),
  text("right again"),
  block("paragraph"),
  text("the end"),
]

